In [1]:
!pip install -q fastparquet
!pip install -q statsforecast

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 26.3 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 1.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 354.6/354.6 kB 12.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 348.2/348.2 kB 15.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 281.0/281.0 kB 13.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.3/37.3 MB 36.8 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.3/40.3 kB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.9/59.9 kB 2.7 MB/s eta 0:00:00

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsforecast import StatsForecast
from statsforecast.models import TSB, AutoETS, AutoARIMA, Naive, SeasonalNaive, Theta, OptimizedTheta, CrostonOptimized, ADIDA, IMAPA, CrostonSBA, HoltWinters

In [3]:
# данные о реальном спросе
real_demand = pd.read_parquet('/kaggle/input/datasets/faibus/diploma/real_demand_data.parquet', engine='fastparquet')

# выгружаем типы рядов
ts_dict_df = pd.read_csv('/kaggle/input/datasets/faibus/diploma/ts_dict_df')[['SKU_id', 'ts_type']]

In [4]:
# Выделяем SKU, принадлежащие к типу lumpy
lumpy_ts = list(ts_dict_df.query(" ts_type == 'erratic' ")['SKU_id'])

# фильтруем датасет по lumpy_ts
real_demand = real_demand.query(" SKU_id.isin(@lumpy_ts) ")

# причесываем датасет
real_demand = real_demand.rename(columns = {'date':'ds', 'real_demand':'y', 'SKU_id':'unique_id'})[['unique_id', 'ds', 'y']]

real_demand

          unique_id         ds      y
22        141905824 2024-01-01    1.0
23        142629362 2024-01-01    1.0
30        142954403 2024-01-01    1.0
33        147282213 2024-01-01    1.0
92        215482427 2024-01-01    1.0
...             ...        ...    ...
5266140  1656117213 2025-09-30   70.0
5266153  1656116903 2025-09-30   86.0
5266155   160506881 2025-09-30   89.0
5266158  1933002627 2025-09-30   95.0
5266176   142629362 2025-09-30  211.0

[297431 rows x 3 columns]

In [27]:
# 1. Создаем список с моделями
models = [
    SeasonalNaive(season_length=7, alias='SeasonalNaive7'),
    Naive(alias='Naive'),
    AutoETS(alias='AutoETS'),
    AutoARIMA(alias='AutoARIMA'),
    OptimizedTheta(alias='OptTheta'),
    ADIDA(alias='ADIDA'),
    IMAPA(alias='IMAPA')
]

# TSB - эталон для lumpy рядов
# ETS - семейство экспоненциальных сглаживаний
# SeasonalNaive - примитивный лаговый прогноз
# Naive - прогноз это последнее значение ряда
# Theta - разбивает ряд на компоненты (линии ряда), каждая компонента прогнозируется отдельно, потом прогнозы комбинируются для получения результата
# ARIMA - семейство ARIMA моделей

In [28]:
# задаем параметры
horizon = 14
step_size = 7
n_windows = 5

# определяем минимально необходимую длину ряда
min_required = n_windows * step_size + horizon

# Группировка и подсчёт длины
series_len = real_demand.groupby('unique_id').size()
long_series = series_len[series_len >= min_required].index

# Оставляем только длинные ряды
real_demand_filtered = real_demand[real_demand['unique_id'].isin(long_series)]

# Создаём экземпляр StatsForecast со списком моделей
sf = StatsForecast(models=models, freq='D', n_jobs=1, verbose = True, fallback_model=Naive())

# Теперь запускаем кросс-валидацию на отфильтрованных данных
cv_results = sf.cross_validation(
    df=real_demand_filtered,
    h=horizon,
    step_size=step_size,
    n_windows=n_windows
)

Cross Validation Time Series 1:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 2:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 3:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 4:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 5:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 6:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 7:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 8:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 9:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 10:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 11:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 12:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 13:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 14:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 15:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 16:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 17:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 18:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 19:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 20:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 21:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 22:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 23:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 24:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 25:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 26:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 27:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 28:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 29:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 30:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 31:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 32:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 33:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 34:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 35:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 36:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 37:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 38:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 39:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 40:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 41:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 42:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 43:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 44:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 45:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 46:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 47:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 48:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 49:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 50:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 51:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 52:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 53:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 54:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 55:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 56:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 57:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 58:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 59:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 60:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 61:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 62:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 63:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 64:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 65:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 66:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 67:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 68:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 69:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 70:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 71:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 72:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 73:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 74:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 75:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 76:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 77:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 78:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 79:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 80:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 81:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 82:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 83:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 84:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 85:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 86:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 87:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 88:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 89:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 90:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 91:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 92:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 93:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 94:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 95:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 96:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 97:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 98:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 99:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 100:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 101:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 102:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 103:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 104:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 105:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 106:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 107:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 108:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 109:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 110:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 111:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 112:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 113:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 114:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 115:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 116:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 117:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 118:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 119:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 120:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 121:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 122:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 123:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 124:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 125:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 126:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 127:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 128:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 129:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 130:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 131:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 132:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 133:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 134:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 135:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 136:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 137:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 138:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 139:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 140:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 141:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 142:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 143:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 144:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 145:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 146:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 147:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 148:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 149:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 150:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 151:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 152:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 153:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 154:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 155:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 156:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 157:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 158:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 159:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 160:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 161:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 162:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 163:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 164:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 165:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 166:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 167:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 168:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 169:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 170:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 171:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 172:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 173:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 174:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 175:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 176:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 177:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 178:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 179:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 180:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 181:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 182:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 183:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 184:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 185:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 186:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 187:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 188:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 189:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 190:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 191:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 192:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 193:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 194:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 195:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 196:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 197:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 198:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 199:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 200:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 201:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 202:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 203:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 204:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 205:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 206:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 207:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 208:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 209:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 210:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 211:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 212:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 213:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 214:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 215:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 216:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 217:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 218:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 219:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 220:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 221:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 222:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 223:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 224:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 225:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 226:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 227:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 228:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 229:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 230:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 231:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 232:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 233:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 234:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 235:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 236:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 237:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 238:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 239:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 240:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 241:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 242:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 243:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 244:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 245:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 246:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 247:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 248:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 249:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 250:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 251:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 252:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 253:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 254:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 255:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 256:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 257:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 258:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 259:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 260:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 261:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 262:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 263:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 264:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 265:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 266:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 267:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 268:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 269:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 270:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 271:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 272:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 273:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 274:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 275:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 276:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 277:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 278:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 279:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 280:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 281:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 282:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 283:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 284:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 285:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 286:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 287:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 288:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 289:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 290:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 291:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 292:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 293:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 294:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 295:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 296:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 297:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 298:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 299:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 300:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 301:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 302:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 303:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 304:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 305:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 306:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 307:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 308:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 309:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 310:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 311:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 312:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 313:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 314:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 315:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 316:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 317:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 318:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 319:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 320:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 321:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 322:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 323:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 324:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 325:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 326:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 327:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 328:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 329:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 330:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 331:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 332:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 333:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 334:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 335:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 336:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 337:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 338:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 339:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 340:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 341:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 342:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 343:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 344:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 345:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 346:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 347:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 348:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 349:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 350:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 351:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 352:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 353:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 354:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 355:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 356:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 357:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 358:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 359:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 360:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 361:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 362:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 363:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 364:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 365:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 366:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 367:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 368:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 369:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 370:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 371:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 372:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 373:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 374:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 375:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 376:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 377:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 378:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 379:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 380:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 381:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 382:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 383:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 384:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 385:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 386:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 387:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 388:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 389:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 390:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 391:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 392:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 393:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 394:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 395:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 396:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 397:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 398:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 399:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 400:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 401:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 402:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 403:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 404:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 405:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 406:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 407:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 408:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 409:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 410:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 411:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 412:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 413:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 414:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 415:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 416:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 417:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 418:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 419:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 420:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 421:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 422:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 423:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 424:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 425:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 426:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 427:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 428:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 429:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 430:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 431:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 432:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 433:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 434:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 435:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 436:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 437:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 438:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 439:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 440:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 441:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 442:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 443:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 444:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 445:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 446:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 447:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 448:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 449:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 450:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 451:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 452:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 453:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 454:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 455:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 456:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 457:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 458:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 459:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 460:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 461:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 462:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 463:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 464:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 465:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 466:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 467:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 468:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 469:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 470:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 471:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 472:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 473:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 474:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 475:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 476:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 477:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 478:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 479:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 480:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 481:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 482:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 483:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 484:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 485:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 486:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 487:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 488:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 489:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 490:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 491:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 492:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 493:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 494:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 495:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 496:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 497:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 498:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 499:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 500:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 501:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 502:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 503:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 504:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 505:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 506:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 507:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 508:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 509:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 510:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 511:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 512:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 513:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 514:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 515:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 516:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 517:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 518:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 519:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 520:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 521:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 522:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 523:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 524:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 525:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 526:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 527:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 528:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 529:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 530:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 531:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 532:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 533:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 534:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 535:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 536:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 537:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 538:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 539:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 540:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 541:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 542:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 543:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 544:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 545:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 546:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 547:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 548:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 549:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 550:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 551:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 552:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 553:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 554:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 555:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 556:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 557:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 558:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 559:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 560:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 561:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 562:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 563:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 564:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 565:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 566:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 567:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 568:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 569:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 570:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 571:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 572:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 573:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 574:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 575:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 576:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 577:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 578:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 579:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 580:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 581:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 582:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 583:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 584:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 585:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 586:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 587:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 588:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 589:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 590:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 591:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 592:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 593:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 594:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 595:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 596:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 597:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 598:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 599:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 600:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 601:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 602:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 603:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 604:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 605:   0%|          | 0/5 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/statsforecast/ets.py:653: RuntimeWarning: divide by zero encountered in scalar divide
  sigma2 = np.sum(e**2) / (ny - np_ - 1)

Cross Validation Time Series 606:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 607:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 608:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 609:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 610:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 611:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 612:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 613:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 614:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 615:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 616:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 617:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 618:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 619:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 620:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 621:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 622:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 623:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 624:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 625:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 626:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 627:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 628:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 629:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 630:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 631:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 632:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 633:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 634:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 635:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 636:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 637:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 638:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 639:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 640:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 641:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 642:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 643:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 644:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 645:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 646:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 647:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 648:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 649:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 650:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 651:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 652:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 653:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 654:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 655:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 656:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 657:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 658:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 659:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 660:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 661:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 662:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 663:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 664:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 665:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 666:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 667:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 668:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 669:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 670:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 671:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 672:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 673:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 674:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 675:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 676:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 677:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 678:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 679:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 680:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 681:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 682:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 683:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 684:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 685:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 686:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 687:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 688:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 689:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 690:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 691:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 692:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 693:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 694:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 695:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 696:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 697:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 698:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 699:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 700:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 701:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 702:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 703:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 704:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 705:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 706:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 707:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 708:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 709:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 710:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 711:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 712:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 713:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 714:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 715:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 716:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 717:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 718:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 719:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 720:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 721:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 722:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 723:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 724:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 725:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 726:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 727:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 728:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 729:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 730:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 731:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 732:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 733:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 734:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 735:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 736:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 737:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 738:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 739:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 740:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 741:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 742:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 743:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 744:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 745:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 746:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 747:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 748:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 749:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 750:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 751:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 752:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 753:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 754:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 755:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 756:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 757:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 758:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 759:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 760:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 761:   0%|          | 0/5 [00:00<?, ?it/s]

Cross Validation Time Series 762:   0%|          | 0/5 [00:00<?, ?it/s]

In [31]:
cv_results

,unique_id,ds,cutoff,y,SeasonalNaive7,Naive,AutoETS,AutoARIMA,OptTheta,ADIDA,IMAPA
0,140322963,2025-08-20,2025-08-19,6.0,4.0,3.0,2.610655,2.975122,2.449317,2.568764,2.49151
1,140322963,2025-08-21,2025-08-19,1.0,3.0,3.0,2.610655,2.813935,2.452822,2.568764,2.49151
2,140322963,2025-08-22,2025-08-19,1.0,4.0,3.0,2.610655,2.830689,2.456326,2.568764,2.49151
3,140322963,2025-08-23,2025-08-19,3.0,0.0,3.0,2.610655,2.835361,2.459831,2.568764,2.49151
4,140322963,2025-08-24,2025-08-19,3.0,0.0,3.0,2.610655,2.840033,2.463335,2.568764,2.49151
...,...,...,...,...,...,...,...,...,...,...,...
53335,2640085912,2025-09-26,2025-09-16,2.0,1.0,1.0,1.490625,2.748398,2.179360,1.830080,1.83008
53336,2640085912,2025-09-27,2025-09-16,3.0,3.0,1.0,1.490625,2.748451,2.238215,1.830080,1.83008
53337,2640085912,2025-09-28,2025-09-16,7.0,1.0,1.0,1.490625,2.748470,2.297070,1.830080,1.83008
53338,2640085912,2025-09-29,2025-09-16,7.0,1.0,1.0,1.490625,2.748478,2.355925,1.830080,1.83008
53339,2640085912,2025-09-30,2025-09-16,6.0,1.0,1.0,1.490625,2.748480,2.414780,1.830080,1.83008

In [29]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

# -------------------------------
# 1. Определение метрик
# -------------------------------

def mae(y_true, y_pred):
    return mean_absolute_error(y_true, y_pred)

def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

def smape(y_true, y_pred):
    y_true = np.asarray(y_true, dtype='float64')
    y_pred = np.asarray(y_pred, dtype='float64')
    denominator = np.abs(y_true) + np.abs(y_pred)
    mask = denominator > 0
    if mask.sum() == 0:
        return np.nan
    return (2 * np.abs(y_true[mask] - y_pred[mask]) / denominator[mask]).mean() * 100

def wape(y_true, y_pred):
    y_true = np.asarray(y_true, dtype='float64')
    y_pred = np.asarray(y_pred, dtype='float64')
    denominator = np.abs(y_true).sum()
    if denominator == 0:
        return np.nan
    return np.abs(y_true - y_pred).sum() / denominator * 100

# -------------------------------
# 2. Функция для вычисления метрик по каждому окну (без unique_id)
# -------------------------------

def compute_metrics_per_window(cv_results, model_columns, metrics_dict):
    """
    cv_results: DataFrame от sf.cross_validation()
    model_columns: список имён столбцов с прогнозами моделей
    metrics_dict: словарь вида {'mae': mae, 'rmse': rmse, ...}
    Возвращает DataFrame с колонками: cutoff, model, и каждой метрикой.
    Для каждого cutoff (окна) метрика вычисляется по всем точкам всех unique_id.
    """
    records = []
    grouped = cv_results.groupby('cutoff')   # группируем только по окну
    
    for cutoff, group in grouped:
        y_true = group['y'].values
        for model in model_columns:
            y_pred = group[model].values
            row = {'cutoff': cutoff, 'model': model}
            for metric_name, metric_func in metrics_dict.items():
                row[metric_name] = metric_func(y_true, y_pred)
            records.append(row)
    
    return pd.DataFrame(records)

# -------------------------------
# 3. Применение к вашим данным
# -------------------------------

# Предполагаем, что cv_results уже получен после cross_validation
# Определяем столбцы моделей (все, кроме служебных)
model_columns = [col for col in cv_results.columns 
                 if col not in ['unique_id', 'ds', 'cutoff', 'y']]

metrics = {
    'mae': mae,
    'rmse': rmse,
    'smape': smape,
    'wape': wape
}

# Вычисляем метрики для каждого окна (без разбивки по unique_id)
metrics_per_window = compute_metrics_per_window(cv_results, model_columns, metrics)

# -------------------------------
# 4. Агрегация результатов
# -------------------------------

# 4.1. Среднее по всем окнам для каждой модели
summary_mean = metrics_per_window.groupby('model')[['mae', 'rmse', 'smape', 'wape']].mean()


# 4.2. Детальная статистика (mean, std, min, max) по окнам
summary_stats = metrics_per_window.groupby('model')[['mae', 'rmse', 'smape', 'wape']].agg(['mean', 'std', 'min', 'max'])


summary_mean

                     mae      rmse      smape       wape
model
ADIDA           3.836254  5.589711  75.630421  81.413007
AutoARIMA       4.061213  5.951473  77.337605  84.669247
AutoETS         4.089220  6.166802  77.164126  83.082808
IMAPA           3.846970  5.601466  75.710643  81.604456
Naive           4.594491  6.502619  92.319522  99.474132
OptTheta        4.029831  5.861351  78.553647  84.279532
SeasonalNaive7  4.685972  6.988374  93.739376  95.424916